//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SivanArazi_RecordStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class DealsDetailsTBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DealsDetailsTBL()
        {
            this.DealsTBL = new HashSet<DealsTBL>();
        }
    
        public int Id { get; set; }
        public int Product { get; set; }
        public int Amount { get; set; }
        public System.DateTime Date { get; set; }
        public int Cost { get; set; }
        public Nullable<int> Discount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DealsTBL> DealsTBL { get; set; }
        public virtual ProductsTBL ProductsTBL { get; set; }
    }
}
