//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SivanArazi_RecordStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class DealsTBL
    {
        public int Id { get; set; }
        public string Coustomer { get; set; }
        public string Employee { get; set; }
        public int Cost { get; set; }
        public int Type { get; set; }
        public Nullable<int> Shipping { get; set; }
    
        public virtual CoustomerTBL CoustomerTBL { get; set; }
        public virtual EmployeesTBL EmployeesTBL { get; set; }
        public virtual OrderTypeTBL OrderTypeTBL { get; set; }
    }
}
