//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SivanArazi_RecordStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpensesTBL
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime Date { get; set; }
        public int Cost { get; set; }
        public Nullable<int> Employee { get; set; }
    
        public virtual EmployeesTBL EmployeesTBL { get; set; }
    }
}
