//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SivanArazi_RecordStore
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataBaseEntities : DbContext
    {
        public DataBaseEntities()
            : base("name=DataBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AlbumsTBL> AlbumsTBL { get; set; }
        public virtual DbSet<CustomersTBL> CustomersTBL { get; set; }
        public virtual DbSet<DealsDetailsTBL> DealsDetailsTBL { get; set; }
        public virtual DbSet<DealsTBL> DealsTBL { get; set; }
        public virtual DbSet<EmployeesTBL> EmployeesTBL { get; set; }
        public virtual DbSet<ExpensesTBL> ExpensesTBL { get; set; }
        public virtual DbSet<OrdersFromSuppliersDetailsTBL> OrdersFromSuppliersDetailsTBL { get; set; }
        public virtual DbSet<OrdersFromSuppliersTBL> OrdersFromSuppliersTBL { get; set; }
        public virtual DbSet<StockTBL> StockTBL { get; set; }
        public virtual DbSet<SuppliersTBL> SuppliersTBL { get; set; }
    }
}
