//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SivanArazi_RecordStore
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataBaseEntities : DbContext
    {
        public DataBaseEntities()
            : base("name=DataBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CoustomerTBL> CoustomerTBL { get; set; }
        public virtual DbSet<CurrentExpensesTBL> CurrentExpensesTBL { get; set; }
        public virtual DbSet<DealsTBL> DealsTBL { get; set; }
        public virtual DbSet<EmployeesTBL> EmployeesTBL { get; set; }
        public virtual DbSet<OrderDetailsTBL> OrderDetailsTBL { get; set; }
        public virtual DbSet<OrdersFromSuppliersTBL> OrdersFromSuppliersTBL { get; set; }
        public virtual DbSet<OrderTypeTBL> OrderTypeTBL { get; set; }
        public virtual DbSet<ShippingTBL> ShippingTBL { get; set; }
    }
}
