//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SivanArazi_RecordStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdersFromSuppliersTBL
    {
        public int Id { get; set; }
        public int Details { get; set; }
        public int Type { get; set; }
    
        public virtual OrderDetailsTBL OrderDetailsTBL { get; set; }
        public virtual OrderTypeTBL OrderTypeTBL { get; set; }
    }
}
