//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SivanArazi_RecordStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShippingTBL
    {
        public int Id { get; set; }
        public Nullable<int> Deal { get; set; }
        public Nullable<int> ShipCost { get; set; }
    
        public virtual DealsTBL DealsTBL { get; set; }
    }
}
