//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SivanArazi_RecordStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockTBL
    {
        public int Id { get; set; }
        public Nullable<int> Album { get; set; }
        public Nullable<int> Type { get; set; }
    
        public virtual AlbumTBL AlbumTBL { get; set; }
        public virtual TypeTBL TypeTBL { get; set; }
    }
}
